var setTimeout;
var goog;
goog.global;
goog.isArrayLike;
var process;
process.hrtime;
RegExp.prototype.schema$core$Schema$;
RegExp.prototype.schema$core$Schema$spec$arity$1;
RegExp.prototype.schema$core$Schema$explain$arity$1;
var Java;
Java.type;
Object.out;
Object.out.println;
Object.error;
Object.error.println;
Object.exec;
Object.index;
Object.install;
var require;
